name: Loop for

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: running the loop
      run: |
        for i in {1..10}; do
          echo $i
        done
